export default {
  colors: {
    blue: "#4182c2",
    red: "#ff2a34",
    grey: "#999999",
    lightGrey: "#a1a1a1",
    footerBackground: "#3C3B49",
    black: "black",
    white: "white",
    opaqueLightBlack: "rgba(0, 0, 0, 0.5)",
    opaqueBlack: "rgba(0, 0, 0, 0.95)",
  },
  breakPoints: {
    mobile: "max-width: 700px",
    tablet: "max-width: 1000px",
    desktop: "max-width: 1500px",
    ultraWide: "max-width: 1700px",
  },
  fontSize: {
    h1: "4rem",
    h2: "2.75rem",
    h3: "1.5rem",
    p: ".9rem",
    article: "1.125rem",
    quoteHeadline: ".95rem",
    author: "1rem",
    title: "1rem",
    quote: "1.2rem",
    videoText: "1.5rem",
    playButton: "6rem",
    mobile: {
      h1: "2.5rem",
      h2: "1.5rem",
      h3: "1rem",
      videoText: "1rem",
      quote: "1rem",
      article: "1rem",
      playButton: "4rem",
    },
  },
  idleTime: 2000,
  animation: {
    duration: ".5s",
  },
};
